### PR TITLE
Only add directories with changed files

### PR DESCRIPTION
**Pull request by jdillard**
The Transifex CLI install adds some helper files (`README.md` and `LICENCE` at this point in time) that were getting added in `git add .`, when they shouldn't be added.

## Summary of changes

- Delete the Transifex CLI `README.md` (shouldn't have been added by the update workflow)
- Only commit changed files in `locales` and in the `sphinx` submodule (so that the `README.md` doesn't come back)

### CODE REVIEW

**Comment by AA-Turner** [comment]
Could we make the second commit standalone?

A

**Comment by jdillard** [comment]
As in a separate PR?

**Comment by AA-Turner** [comment]
Oh, the auto-update commit restored it. Perhaps that needs updating?

A

**Comment by jdillard** [comment]
It didn't necessarily "restore" the old `README.md`, but this install step also installs `README.md` and `LICENCE` files:
https://github.com/sphinx-doc/sphinx-doc-translations/blob/3e964f79681ad2c2d11ebcd8e966f62f18c549e9/.github/workflows/main.yml#L50

The reason they weren't added before is `curl` didn't download those two files because they already existed in the repo, now that `README.md` no longer exists, it was getting downloaded and added in `git add .`

**Comment by rffontenelle** [comment]
Another solution is to run installation in another directory with `working-directory` option. Since the installer adds the download path to PATH, tx will be available from now on without the LICENSE, README.md and any other in the filter.

```yaml
   - name: Install Transifex CLI
      working-directory: /usr/local/bin
      run: |
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
        tx --version
```

**Pull request merged**
