### PR TITLE
Setup Tamil translated documentation projects on RTD

### PR DESCRIPTION
**Pull request by tkoyama010**
Translation of Tamil reached over 50% (https://app.transifex.com/sphinx-doc/sphinx-doc/dashboard/). It's time to Setup Tamil translated documentation projects on RTD.

### CODE REVIEW

**Comment by AA-Turner** [comment]
There were previously many errors in Tamil (#36), have these been resolved?

A

**Comment by tkoyama010** [comment]
I just looked at the Transfix percentages, so I didn't know that. I'd love to hear what @rffontenelle say about it :)

**Comment by shimizukawa** [comment]
After checking, unfortunately it seems that Tamil translations are still being registered as machine translations.
image

When I built with this `ta` message catalog, 2638 warnings were output.
In addition, the output results also show that the reStructuredText notation was built in a broken state.
image

For this reason, I think that the Tamil translation cannot be used as a translation document.

**Comment by tkoyama010** [comment]
> After checking, unfortunately it seems that Tamil translations are still being registered as machine translations. image
> 
> When I built with this `ta` message catalog, 2638 warnings were output. In addition, the output results also show that the reStructuredText notation was built in a broken state. image
> 
> For this reason, I think that the Tamil translation cannot be used as a translation document.

OK. Let's wait until it is fixed. Thanks!

**Comment by rffontenelle** [comment]
I contacted the translator regarding Errors reported by Transifex and it is now fixed. In the occasion. We indeed still have these machine translation-like translated strings that needs some human. Today I contacted the translator again asking to fix the translations. Until then, not including.

**Pull request closed without merging**
