### PR TITLE
Install graphviz in .readthedocs.yml

### PR DESCRIPTION
**Pull request by rffontenelle**
See #34

### CODE REVIEW

**Review by shimizukawa — APPROVED** [review]
👍

**Comment by rffontenelle** [comment]
Sadly, it seems sudo is not allowed in RTD build.commands and apt fails due to lack of permission. Will need to figure out another way out.

**Comment by rffontenelle** [comment]
Attempts so far:
- Tried installing graphviz using `sudo`, but sudo is not available by design in Read The Docs's `build.command`
- Tried installing without `sudo`, but failed to do (by design) lack of permissions (no root or sudo available)
- Tried using `build.apt_packages`, but `build.commands` seems to ignore it (dot not available)

**Comment by rffontenelle** [comment]
Did a better job in  #49. Closing.

**Pull request closed without merging**
